version: '2'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit-flowershop"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - localFlowershop
networks:
  localFlowershop:
    driver: bridge